google.maps.__gjsload__('geometry', function(_){var Zt=function(a,b){return Math.abs(_.od(b-a,-180,180))},$t=function(a,b,c,d,e){if(!d){c=Zt(a.lng(),c)/Zt(a.lng(),b.lng());if(!e)return e=Math.sin(_.pc(a.lat())),e=Math.log((1+e)/(1-e))/2,b=Math.sin(_.pc(b.lat())),_.qc(2*Math.atan(Math.exp(e+c*(Math.log((1+b)/(1-b))/2-e)))-Math.PI/2);a=e.fromLatLngToPoint(a);b=e.fromLatLngToPoint(b);return e.fromPointToLatLng(new _.I(a.x+c*(b.x-a.x),a.y+c*(b.y-a.y))).lat()}e=_.pc(a.lat());a=_.pc(a.lng());d=_.pc(b.lat());b=_.pc(b.lng());c=_.pc(c);return _.od(_.qc(Math.atan2(Math.sin(e)*
Math.cos(d)*Math.sin(c-b)-Math.sin(d)*Math.cos(e)*Math.sin(c-a),Math.cos(e)*Math.cos(d)*Math.sin(a-b))),-90,90)},au=_.n(),bu={containsLocation:function(a,b){var c=_.od(a.lng(),-180,180),d=!!b.get("geodesic"),e=b.get("latLngs"),f=b.get("map");f=!d&&f?f.getProjection():null;for(var g=!1,h=0,k=e.getLength();h<k;++h)for(var l=e.getAt(h),m=0,q=l.getLength();m<q;++m){var t=l.getAt(m),u=l.getAt((m+1)%q),v=_.od(t.lng(),-180,180),w=_.od(u.lng(),-180,180),x=Math.max(v,w);v=Math.min(v,w);(180<x-v?c>=x||c<v:
c<x&&c>=v)&&$t(t,u,c,d,f)<a.lat()&&(g=!g)}return g||bu.isLocationOnEdge(a,b)}};_.Za("PolyGeometry.containsLocation",bu.containsLocation);
bu.isLocationOnEdge=function(a,b,c){c=c||1E-9;var d=_.od(a.lng(),-180,180),e=b instanceof _.vi,f=!!b.get("geodesic"),g=b.get("latLngs");b=b.get("map");b=!f&&b?b.getProjection():null;for(var h=0,k=g.getLength();h<k;++h)for(var l=g.getAt(h),m=l.getLength(),q=e?m:m-1,t=0;t<q;++t){var u=l.getAt(t),v=l.getAt((t+1)%m),w=_.od(u.lng(),-180,180),x=_.od(v.lng(),-180,180),E=Math.max(w,x),J=Math.min(w,x);if(w=1E-9>=Math.abs(_.od(w-x,-180,180))&&(Math.abs(_.od(w-d,-180,180))<=c||Math.abs(_.od(x-d,-180,180))<=
c)){w=a.lat();x=Math.min(u.lat(),v.lat())-c;var M=Math.max(u.lat(),v.lat())+c;w=w>=x&&w<=M}if(w)return!0;if(180<E-J?d+c>=E||d-c<=J:d+c>=J&&d-c<=E)if(u=$t(u,v,d,f,b),Math.abs(u-a.lat())<c)return!0}return!1};_.Za("PolyGeometry.isLocationOnEdge",bu.isLocationOnEdge);var cu={computeHeading:function(a,b){var c=_.Zd(a),d=_.$d(a);a=_.Zd(b);b=_.$d(b)-d;return _.od(_.qc(Math.atan2(Math.sin(b)*Math.cos(a),Math.cos(c)*Math.sin(a)-Math.sin(c)*Math.cos(a)*Math.cos(b))),-180,180)}};_.Za("Spherical.computeHeading",cu.computeHeading);
cu.computeOffset=function(a,b,c,d){b/=d||6378137;c=_.pc(c);var e=_.Zd(a);a=_.$d(a);d=Math.cos(b);b=Math.sin(b);var f=Math.sin(e);e=Math.cos(e);var g=d*f+b*e*Math.cos(c);return new _.L(_.qc(Math.asin(g)),_.qc(a+Math.atan2(b*e*Math.sin(c),d-f*g)))};_.Za("Spherical.computeOffset",cu.computeOffset);
cu.computeOffsetOrigin=function(a,b,c,d){c=_.pc(c);b/=d||6378137;d=Math.cos(b);var e=Math.sin(b)*Math.cos(c);b=Math.sin(b)*Math.sin(c);c=Math.sin(_.Zd(a));var f=e*e*d*d+d*d*d*d-d*d*c*c;if(0>f)return null;var g=e*c+Math.sqrt(f);g/=d*d+e*e;var h=(c-e*g)/d;g=Math.atan2(h,g);if(g<-Math.PI/2||g>Math.PI/2)g=e*c-Math.sqrt(f),g=Math.atan2(h,g/(d*d+e*e));if(g<-Math.PI/2||g>Math.PI/2)return null;a=_.$d(a)-Math.atan2(b,d*Math.cos(g)-e*Math.sin(g));return new _.L(_.qc(g),_.qc(a))};
_.Za("Spherical.computeOffsetOrigin",cu.computeOffsetOrigin);cu.interpolate=function(a,b,c){var d=_.Zd(a),e=_.$d(a),f=_.Zd(b),g=_.$d(b),h=Math.cos(d),k=Math.cos(f);b=cu.mf(a,b);var l=Math.sin(b);if(1E-6>l)return new _.L(a.lat(),a.lng());a=Math.sin((1-c)*b)/l;c=Math.sin(c*b)/l;b=a*h*Math.cos(e)+c*k*Math.cos(g);e=a*h*Math.sin(e)+c*k*Math.sin(g);return new _.L(_.qc(Math.atan2(a*Math.sin(d)+c*Math.sin(f),Math.sqrt(b*b+e*e))),_.qc(Math.atan2(e,b)))};_.Za("Spherical.interpolate",cu.interpolate);
cu.mf=function(a,b){var c=_.Zd(a);a=_.$d(a);var d=_.Zd(b);b=_.$d(b);return 2*Math.asin(Math.sqrt(Math.pow(Math.sin((c-d)/2),2)+Math.cos(c)*Math.cos(d)*Math.pow(Math.sin((a-b)/2),2)))};cu.computeDistanceBetween=function(a,b,c){c=c||6378137;return cu.mf(a,b)*c};_.Za("Spherical.computeDistanceBetween",cu.computeDistanceBetween);cu.computeLength=function(a,b){b=b||6378137;var c=0;a instanceof _.Oe&&(a=a.getArray());for(var d=0,e=a.length-1;d<e;++d)c+=cu.computeDistanceBetween(a[d],a[d+1],b);return c};
_.Za("Spherical.computeLength",cu.computeLength);cu.computeArea=function(a,b){return Math.abs(cu.computeSignedArea(a,b))};_.Za("Spherical.computeArea",cu.computeArea);cu.computeSignedArea=function(a,b){b=b||6378137;a instanceof _.Oe&&(a=a.getArray());for(var c=a[0],d=0,e=1,f=a.length-1;e<f;++e)d+=cu.Fj(c,a[e],a[e+1]);return d*b*b};_.Za("Spherical.computeSignedArea",cu.computeSignedArea);cu.Fj=function(a,b,c){return cu.Gj(a,b,c)*cu.uk(a,b,c)};
cu.Gj=function(a,b,c){var d=[a,b,c,a];a=[];for(c=b=0;3>c;++c)a[c]=cu.mf(d[c],d[c+1]),b+=a[c];b/=2;d=Math.tan(b/2);for(c=0;3>c;++c)d*=Math.tan((b-a[c])/2);return 4*Math.atan(Math.sqrt(Math.abs(d)))};
cu.uk=function(a,b,c){a=[a,b,c];b=[];for(c=0;3>c;++c){var d=a[c],e=_.Zd(d);d=_.$d(d);var f=b[c]=[];f[0]=Math.cos(e)*Math.cos(d);f[1]=Math.cos(e)*Math.sin(d);f[2]=Math.sin(e)}return 0<b[0][0]*b[1][1]*b[2][2]+b[1][0]*b[2][1]*b[0][2]+b[2][0]*b[0][1]*b[1][2]-b[0][0]*b[2][1]*b[1][2]-b[1][0]*b[0][1]*b[2][2]-b[2][0]*b[1][1]*b[0][2]?1:-1};var du={decodePath:function(a){for(var b=_.kd(a),c=Array(Math.floor(a.length/2)),d=0,e=0,f=0,g=0;d<b;++g){var h=1,k=0;do{var l=a.charCodeAt(d++)-63-1;h+=l<<k;k+=5}while(31<=l);e+=h&1?~(h>>1):h>>1;h=1;k=0;do l=a.charCodeAt(d++)-63-1,h+=l<<k,k+=5;while(31<=l);f+=h&1?~(h>>1):h>>1;c[g]=new _.L(1E-5*e,1E-5*f,!0)}c.length=g;return c}};_.Za("PolylineCodec.decodePath",du.decodePath);
du.encodePath=function(a){a instanceof _.Oe&&(a=a.getArray());return du.Ol(a,function(b){return[Math.round(1E5*b.lat()),Math.round(1E5*b.lng())]})};_.Za("PolylineCodec.encodePath",du.encodePath);du.Ol=function(a,b){for(var c=[],d=[0,0],e,f=0,g=_.kd(a);f<g;++f)e=b?b(a[f]):a[f],du.Ph(e[0]-d[0],c),du.Ph(e[1]-d[1],c),d=e;return c.join("")};du.Ph=function(a,b){du.Pl(0>a?~(a<<1):a<<1,b)};du.Pl=function(a,b){for(;32<=a;)b.push(String.fromCharCode((32|a&31)+63)),a>>=5;b.push(String.fromCharCode(a+63))};_.y.google.maps.geometry={encoding:du,spherical:cu,poly:bu};_.r=au.prototype;_.r.decodePath=du.decodePath;_.r.encodePath=du.encodePath;_.r.computeDistanceBetween=cu.computeDistanceBetween;_.r.interpolate=cu.interpolate;_.r.computeHeading=cu.computeHeading;_.r.computeOffset=cu.computeOffset;_.r.computeOffsetOrigin=cu.computeOffsetOrigin;_.vf("geometry",new au);});
